### ISSUE TITLE
Typed Controller should remove auto-patching

### ISSUE THREAD

**Issue by njtran** [aws/karpenter-core#153]
### Tell us about your request

Karpenter typed controller patches the reconciled object. We should investigate updating instead of patching and rely on optimistic locking.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Currently, we just patch, meaning two concurrently occuring patches could succeed, when only one should. 

### Are you currently working around this issue?

Not

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Discussed offline, we will keep the `controller.Typed` mechanism as an abstraction but we will yank out the auto-patching mechanism. It is the responsibility of the controller reconcile to do its own handling of Update/Patch. If a controller wants to do patching always, it can do so with a `defer` statement in the Reconcile that patches regardless of whether it fails or not.
