### ISSUE TITLE
Inflight checks use beta instance-type label instead of stable

### ISSUE THREAD

**Issue by Noksa** [aws/karpenter-core#157]
### Version

__Karpenter Version:__ v0.22.0

### Expected Behavior

I'm not sure but wouldn't it better to use stable label instead of beta?
Or use `NormalizedLabels` to translate deprecated labels to stable in inflight controller as well

### Actual Behavior

https://github.com/aws/karpenter-core/blob/main/pkg/controllers/inflightchecks/nodeshape.go#L55

### Steps to Reproduce the Problem

Not sure how it can be reproduced on AWS, but if we are talking about custom implementations, currently we should place beta label on node as well to make inflight checks work. Otherwise, instance type can't be found because there is no `beta.kubernetes.io/instance-type` label on nodes.

### Resource Specs and Logs

No logs

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Huge find. This is definitely a bug. Do you want to submit a fix?

**Comment by Noksa** [comment]
@ellistarn 
Sure, will do it
