### ISSUE TITLE
Prefer go 1.20 `errors.Join` over `multierr.Append` or `multierr.Combine`

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-core#216]
### Tell us about your request

Go 1.20 has introduced joining errors together into a single error with the `errors.Join` method.

We should deprecate our current usage of `multierr` in favor of using the `errors.Join` method in the standard library.

https://lukas.zapletalovi.com/posts/2022/wrapping-multiple-errors/

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
I think we'll need to stick with multierr because of the newlines (https://go.dev/play/p/zKWuqI_Y8EK)

```
package main

import (
	"errors"
	"fmt"

	"go.uber.org/multierr"
)

func main() {
	fmt.Println(multierr.Append(fmt.Errorf("[multierr] first error"), fmt.Errorf("[multierr] second error")))
	fmt.Println(errors.Join(fmt.Errorf("[errors.Join] first error"), fmt.Errorf("[errors.Join] second error")))
}
```

stdout:
```
[multierr] first error; [multierr] second error
[errors.Join] first error
[errors.Join] second error
```

**Comment by ellistarn** [comment]
This seems like a huge miss from golang 1.20. Worth following up at https://github.com/golang/go?

**Comment by ellistarn** [comment]
No idea why it didn't follow https://pkg.go.dev/strings#example-Join. `errors.JoinWith(errs, "; ")
