### ISSUE TITLE
What is the relationship between  karpenter-core and  karpenter?

### ISSUE THREAD

**Issue by soulseen** [aws/karpenter-core#227]
### What karpenter features are relevant?

I found there is two repo about karpenter: [karpenter](https://github.com/aws/karpenter/tree/main/charts/karpenter) and [karpenter-core](https://github.com/aws/karpenter-core),
so may I ask what is the relationship between karpenter-core and karpenter?
is [karpenter](https://github.com/aws/karpenter/tree/main/charts/karpenter) contains the [karpenter-core](https://github.com/aws/karpenter-core)?

### How should the docs be improved?

add more descriptions about karpenter and karpenter-core.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by soulseen** [comment]
@tzneal is there any doc on how to build a "Karpenter" for another cloud provider?

**Comment by tzneal** [comment]
Not at the moment, the best place to look is the aws/karpenter repo.

**Comment by ellistarn** [comment]
The best example is the one at github.com/aws/karpenter, where we implement the generic cloudprovider interface https://github.com/aws/karpenter-core/blob/main/pkg/cloudprovider/types.go.

I'd start with main, and get an understanding for the generic and aws specific parts of the codebase. The vast majority of the code is in karpenter-core. We wish we had a better story documented here, but it's still early days. I'd recommend starting by joining #karpenter-dev on the kubernetes slack, and chatting with the team live.
