### ISSUE TITLE
Make logging more consistent

### ISSUE THREAD

**Issue by Almenon** [aws/karpenter-core#253]
### Tell us about your request

This is a total nitpick, but sometimes logs come in a inconsistent format. It would be nice if it all used one format so I could just have one log parsing rule.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Unparsed logs being reported as errors

### Are you currently working around this issue?

Excluding said logs

### Attachments

```
Registering 2 clients
2023/03/20 22:26:43 Registering 2 informer factories
2023/03/20 22:26:43 Registering 3 informers
2023/03/20 22:26:43 Registering 6 controllers
I0320 22:26:43.613582       1 leaderelection.go:248] attempting to acquire leader lease karpenter/karpenter-leader-election...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Almenon** [comment]
The default format is something like this: `2023-03-28T00:45:00.214Z	INFO	controller	Starting informers...	{"commit": "5a7faa0-dirty"}`. Would be nice for all logs to match that.

**Comment by agustin-dona-peya** [comment]
Hello Almenon, please look at this issue https://github.com/aws/karpenter/issues/3560 i reported the same some time ago
