### ISSUE TITLE
Add metrics about unconsolidatable nodes

### ISSUE THREAD

**Issue by cebernardi** [aws/karpenter-core#290]
### Tell us about your request

So far Karpenter emits events about unconsolidatable nodes, but not metrics.

What about a new `karpenter_deprovisioning_unconsolidatable_nodes` metric, labeled by reason?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We're trying to increment the efficiency of our Karpenter installation consolidation process.
We've noticed that a relevant contributor to a missed deprovisioning by consolidation, is PodDisruptionBudget misconfiguration.

Having metrics about evaluated but not consolidated nodes would help us to understand the different dynamics in place and come up with strategies to make the process more effective.

### Are you currently working around this issue?

We're collecting data based on the emitted events, but is not ideal.

### Additional Context

I would be happy to contribute, if the feature request is accepted

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by cebernardi** [comment]
Is this the right project to open feature requests again? or should it be aws/karpenter?

**Comment by tzneal** [comment]
This project is fine, it will be implemented in this code.

**Comment by njtran** [comment]
Hey @cebernardi, we added in some metrics here https://github.com/aws/karpenter-core/pull/331 that include how many nodes are eligible, which is the inverse of this. In terms of labeling it by reason, there could be multiple reasons why a node is unconsolidatable, which I don't think is best modeled as one label in Prometheus metrics. We emit events for this in Deprovisioning as well, where I think it's better modeled.

Going to close this, feel free to re-open if you disagree.
