### ISSUE TITLE
add unit tests for limits.go

### ISSUE THREAD

**Issue by khareyash05** [aws/karpenter-core#302]
I would like to add unit tests for `pkg/apis/v1apha5/limits.go`

**Comment by jonathan-innis** [comment]
@khareyash05 Looks like we have some unit tests here for limits already: https://github.com/aws/karpenter-core/blob/main/pkg/apis/v1alpha5/suite_test.go#L495. Would you be interested in expanding our test coverage in other areas of the codebase?

**Comment by khareyash05** [comment]
@jonathan-innis Yes I would like to

**Comment by jonathan-innis** [comment]
For now, [this](https://github.com/aws/karpenter-core/issues/82) is the current active issue for testing. I'll dig into the codebase a bit more later tonight and start opening issues in areas where we need more code coverage. 

Hopefully we can see a lot more issues with the `testing` label soon~

**Comment by khareyash05** [comment]
> @khareyash05 For now, [this](https://github.com/aws/karpenter-core/issues/82) is the current active issue for testing. Let me know if you want me to assign you to it! I'll dig into the codebase a bit more later tonight and start opening issues in areas where we need more code coverage.
> 
> Hopefully we can see a lot more issues with the `testing` label soon!

Thank you and I would like to contribute more and more

**Comment by jonathan-innis** [comment]
Do you mind asking to be assigned on the other issue #82. I can't assign you to it unless your are involved in the conversation.

**Comment by khareyash05** [comment]
@jonathan-innis TBH , I have actually worked on unit testing till now but I am not so sure about E2E tests as I have not designed one in the past. I would have to take some time to understand them. Also I am open to any other unit tests need to be done.

**Comment by khareyash05** [comment]
Thank you @jonathan-innis I have commented on the PR's.
