### ISSUE TITLE
Karpenter won't provision compute for pods referencing a statically-created persistent volume if a storage class doesn't exist

### ISSUE THREAD

**Issue by d-m** [aws/karpenter-core#376]
## Expected behavior

Compute for the pod is provisioned successfully.

## Versions

__Karpenter Version:__ v0.27.5

__Kubernetes Version:__ v1.27.1

### Expected Behavior

Compute for the pod mounting a statically-provisioned persistent volume is provisioned successfully.

### Actual Behavior

We're using Karpenter to schedule compute for a pod that mounts a statically-created, NFS-backed persistent volume. The persistent volume claim and persistent volume are created successfully:

```
$ kubectl get pv
NAME                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM              STORAGECLASS                   REASON   AGE
efs-pv                           5Gi              RWX    Retain            Bound       my-app/efs-pvc        efs-pv            3d21h

$ kubectl get pvc -n my-app
NAME     STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS                   AGE
efs-pvc   Bound     pvc-XXX-XXX-XXX        5Gi        RWX            efs-pv                    3d16h
```

However, Karpenter fails to schedule compute because the storage class wasn't explicitly created:

```
2023-06-20T14:17:30.966Z        DEBUG   controller.provisioner  ignoring pod, StorageClass.storage.k8s.io "efs-pv" not found   {"commit": "698f22f-dirty", "pod": "my-app/my-app-0"}
```

Creating a storage class with for `efs-pv` allowed provisioning to continue.

### Steps to Reproduce the Problem

1. Create a statically-defined persistent volume
2. Create a persistent volume claim that uses the persistent volume
3. Mount PVC in a pod

### Resource Specs and Logs

```
2023-06-20T14:17:30.966Z        DEBUG   controller.provisioner  ignoring pod, StorageClass.storage.k8s.io "efs-pv" not found   {"commit": "698f22f-dirty", "pod": "my-app/my-app-0"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Related: https://github.com/aws/karpenter/issues/4003
