### ISSUE TITLE
Compatibility checks for incompatible Karpenter versions

### ISSUE THREAD

**Issue by billrayburn** [aws/karpenter-core#388]
### Description

**What problem are you trying to solve?**

Implement compatibility checks where Karpenter communicates incompatible versions to users.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
What kind of imcompatable versions? Do you mean Cluster Versions? Would this become part of the cloud provider interface to implmeent a supported versions call? 

Using something like the listOrchestrators api in AKS?
~/dev/karp_enter/karpenter-core az aks get-versions --location eastus --output table     bsoghigian@MacBook-Air
KubernetesVersion    Upgrades
-------------------  -----------------------
1.27.1(preview)      None available
1.26.3               1.27.1(preview)
1.26.0               1.26.3, 1.27.1(preview)
1.25.6               1.26.0, 1.26.3
1.25.5               1.25.6, 1.26.0, 1.26.3
1.24.10              1.25.5, 1.25.6
1.24.9               1.24.10, 1.25.5, 1.25.6

**Comment by engedaam** [comment]
Closed by https://github.com/aws/karpenter/pull/4401
