### ISSUE TITLE
Karpenter is unable to consolidate when a pod is permanently stuck in Pending 

### ISSUE THREAD

**Issue by garvinp-stripe** [aws/karpenter-core#457]
### Description

**Observed Behavior**:
When a pod is stuck permanently in Pending, (pod will never match any node due to some error), Karpenter is unable to consolidate any nodes. This seems to be because during simulation https://github.com/aws/karpenter-core/blob/dca87d6ed6e8b4ed2459458508c2efa9287aa183/pkg/controllers/deprovisioning/helpers.go#L69C20-L69C20 when it performs getPendingPods, https://github.com/aws/karpenter-core/blob/dca87d6ed6e8b4ed2459458508c2efa9287aa183/pkg/controllers/provisioning/provisioner.go#L154, to determine if all pods will be able land in all nodes minus the nodes being consolidated the permanently stuck pod will cause the simulation to fail 

**Expected Behavior**:
I don't believe we should get stuck on consolidation if there is an erroneous pending pod.

**Reproduction Steps** (Please include YAML):
Introduce a pod with node selector that doesn't match any nodes. Attempt to drain pods from cluster such that Karpenter would consolidate. 

**Versions**:
Karpenter v0.29.2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Good investigation. I'll try and get a fix out today for this.
