### ISSUE TITLE
Add fuzzy matching for common well-known labels

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-core#499]
### Description

**What problem are you trying to solve?**

Currently, Karpenter will just inform you that your current requirements aren't being met by the instance types available or your Provisioner without a consideration that you _might_ have misspelled or made a common mistake (providing the wrong prefix/group name) for a label. We should add code that can catch these common mistakes with labels and inform the user that _this_ is the problem instead or providing a generic error that the requirements don't match. 

As an example, this feature would have helped this user in [this issue](https://github.com/aws/karpenter/issues/4362) self-diagnose their problem.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
We do some of that here, https://github.com/aws/karpenter-core/blob/33c85e739e203bdaee3ac15bb37641395f57b2c9/pkg/scheduling/requirements.go#L157

**Comment by jonathan-innis** [comment]
> We do some of that here

Yeah, I realized that after opening this issue. I think we may want to add additional logging when someone swaps out domains entirely, since the edit distance won't catch this right now.

**Comment by sadath-12** [comment]
Hi @jonathan-innis , Can I work on this issue ?
