### ISSUE TITLE
Support softer topology constraint to reduce node churn

### ISSUE THREAD

**Issue by garvinp-stripe** [aws/karpenter-core#517]
### Description

**What problem are you trying to solve?**
Currently Karpenter tighten all topology spread constraint when performing scheduling simulation for scheduling and consolidation. Specifically it doesn't put into consideration if a constraint is ScheduleAnyways vs DoNotSchedule. I understand that Karpenter tries to provide the maximal safety for the minimal cost however in this case I believe it just causes unnecessary node churn and higher cost.

Topology code that ignores level of strictness
https://github.com/aws/karpenter-core/blob/56b844a884f1b9b73a14b7ad37814d6b954e2970/pkg/controllers/provisioning/scheduling/topology.go#L98
and
https://github.com/aws/karpenter-core/blob/56b844a884f1b9b73a14b7ad37814d6b954e2970/pkg/controllers/provisioning/scheduling/topology.go#L282

and relaxation is only considered if the pod doesn't fit any existing or new node claim that can be created by existing provisioners. 
https://github.com/aws/karpenter-core/blob/56b844a884f1b9b73a14b7ad37814d6b954e2970/pkg/controllers/provisioning/scheduling/scheduler.go#L159

**Worst Case Scenario**

Imagine a small cluster that only runs Deployment X with N pods with prefer node spread. We have a lower bound on the minimize size of a node where the smallest node can fit N pods. We use blue green deploys so during a deployment, we would see 2x the normal pod count. During deploy Karpenter would create N nodes because there are N new pods with node spread constraint. When the first node gets created, all of the pods will end up on that node because kube-scheduler will simply schedule these pods onto the first available node since all constraints are ScheduleAnyways.  The N-1 nodes will eventually be consolidated when consolidation controller or emptiness controller notice the nodes. 

This situation is often made worse in a real cluster where some pods, regardless of from what deployment, land on some of the new nodes since consolidation controller tends to runs slower than emptiness controller causing nodes running longer than needed. 

I think what Karpenter is trying to do isn't actually helpful. 

If users set ScheduleAnyways for topology spread to avoid a situation where node capacity or an AZ isn't available causing the deployment/ pod to never schedule but still want a good spread during normal times, then they likely won't see a good spread because the scheduler doesn't know better especially without pre-binding pods to nodes. This means there is a high likelihood that pods simply get scheduled onto the first available node and the rest of the nodes simply would remain empty or is highly underutilized. They would only benefit from this if they set minDomain which requires DoNotSchedule.

Currently, the only way in which pods are able to leverage Karpenter's scaling based on any topology constraint behavior is to use DoNotSchedule where ScheduleAnyways would simply incur cost.

I believe the fix could be simply relaxing during scheduling add

https://github.com/aws/karpenter-core/blob/56b844a884f1b9b73a14b7ad37814d6b954e2970/pkg/controllers/provisioning/scheduling/scheduler.go#L238

where after it attempts to match existing nodes + newNodeClaims it relaxes the pod's preference 
https://github.com/aws/karpenter-core/blob/56b844a884f1b9b73a14b7ad37814d6b954e2970/pkg/controllers/provisioning/scheduling/preferences.go#L36
 
and reattempts to add the pod to existing + new node claims before creating a new node completely 

**How important is this feature to you?**
This is causing a lot of node churn and I think increase in cost when it isn't necessary.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
From what I understand, this is working as designed. Karpenter has to reason about inflight nodes and theoretical nodes that it’ll spin up, where kube-scheduler is only aware of real nodes. IIUC, it sounds like in cases where multiple Preferred pods are spun up, needing new nodes, you want Karpenter to understand the race that could occur with the kube-scheduler and just not spin up the extra node(s) that Karpenter would have created and then later consolidated. 

This sounds like a lesser need to follow preference on scale up, where you only want new nodes on a different batching sequence. As it is, I think you should be able to get the behavior you want by using DoNotSchedule. Although, I can see adding in a control in the future that lets users set either always respecting preferences (as is) or ignoring preferences (treating ScheduleAnyway as DoNotSchedule). 

For your proposed solution, I’m not sure if that would change much, especially in the worst case that you’ve laid out above. I can’t quite see how the different order of relaxation is different than ignoring the preferences as a whole, as the kube-scheduler will still not respect preferences on startup.

**Comment by garvinp-stripe** [comment]
> This sounds like a lesser need to follow preference on scale up, where you only want new nodes on a different batching sequence. As it is, I think you should be able to get the behavior you want by using DoNotSchedule. Although, I can see adding in a control in the future that lets users set either always respecting preferences (as is) or ignoring preferences (treating ScheduleAnyway as DoNotSchedule).

I think thats kind of what we want but I think its worth explaining our thought around what each Scheduling tightness means and see how it matches with Karpenters. There are 3 kind of tightness for us. In the order of 'tightness': ScheduleAnyways, DoNotSchedule with minDomain and DoNotSchedule.

In ScheduleAnyways we expect if minimal number of nodes that is created for the batch of unschedulable pods can allow for the topology spread do it, if not its fine to break the topology spread so we can packed tighter. From the pod to node batching aspect this means that ideally all new pods that are unschedulable are packed as tightly as we can with the least number of node while attempting with best effort to bring up nodes that satisfy the batch of pod's topology constraints. This means not bring up any new nodes just to satisfy ScheduleAnyways constraint. 

In DoNotSchedule with minDomain, if current node batch do not meet any pod's minDomain -> create new node, if not attempt to pack the pod onto current node batch.

DoNotSchedule, if pod do not meet topology constraint create a new node else map to current node batch.

Following what Karpenter does atm and addressing a bit around the patch, which like you mention isn't completely correct, my expectation of the order of batching is for ScheduleAnyways:
1. Fit pod on existing nodes which includes new nodes created in current batch with scheduling constraints tighten (best effort attempting to match scheduling constraint to current new node batch)
2. If that fails to fit, relax the topology constraint to ensure that it wasn't the soft constraint that made pod not be able to add to current node batch.
3. If that still fails -> create new node. 

The different ordering of relaxation is suppose to address this but I know PR is not ideal. The relaxation is too strong (node affinity that are strict are stripped) also I haven't fully grasped what this means from the consolidation side of things. At first glance I think it is reasonable to consolidate when the node exist purely because of pods' soft constraint but I am not sure if that is everyone's  expectation

**Comment by garvinp-stripe** [comment]
Happy to chat over a call instead too since its a lot of information and its a bit complicated + I am terrible at explaining things

**Comment by njtran** [comment]
Hey @garvinp-stripe, while I understand Karpenter can overshoot here, this should be mitigated (if not nonexistent) in Deprovisioning, where we pre-spin nodes to match preferences where kube-scheduler should have the capacity it needs to satisfy preferences. On provisioning, generally the more capacity you have in your cluster, the more likely you'll be able to see these preferences respected, IIUC. 

To solve your issue, you could either choose to update your deployments to DoNotSchedule and also use MinDomains to ensure that the pods are spread across the minimum number of nodes you expect.

w.r.t. your solution, I may not be fully understanding it, but I think you're missing some cases of when pod scheduling succeeds, and step 3 doesn't make sense, as if pod scheduling fails we wouldn't want to create a new node. I'm happy to chat if you wanna ping me on slack and we can talk this one out so that I can see where we're not on the same page. 

w.r.t. your expectations of scheduling tightness, defining three levels of tightness: ScheduleAnyway, DoNotSchedule w/ MinDomain, DoNotSchedule.

I may be wrong here, but I'm not sure your solution fits the case for users who have differing understandings of tightness. Some may want preferences to apply for the `kube-scheduler` only, but don't want Karpenter to potentially increase cost due to preferences, where I think this may impact deprovisioning. 

Topology is confusing :)  let me know if this makes sense, as I've been having to wrap my head around the problem too. Happy to hop on a call!

**Comment by njtran** [comment]
Discussed in working group, looks like using required zonal spread and removing the hostname preferred spec out of the pod fits the use case. @garvinp-stripe ping me and let me know if you didn't capture this right.

**Comment by garvinp-stripe** [comment]
https://github.com/aws/karpenter-core/issues/666
