### ISSUE TITLE
Add Golang formating github action 

### ISSUE THREAD

**Issue by sadath-12** [aws/karpenter-core#574]
### Description

**What problem are you trying to solve?**

Currently there is no separate action that checks if the pr opened has correct golang formatting it would be great if everyone maintains the same formatting as the project grows

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
During testing for PRs, we run a set of steps for formatting: https://github.com/aws/karpenter-core/blob/8e6687ea72b6a212916652ba688fbb123d002c40/Makefile#L32. Testing is also done using: https://github.com/aws/karpenter-core/blob/8e6687ea72b6a212916652ba688fbb123d002c40/Makefile#L4

**Comment by sadath-12** [comment]
Thanks for pointing me out , could you help me pointing out what is the thing that handles formatting ? specifically

**Comment by jonathan-innis** [comment]
We currently do formatting as part of the `make presubmit` action. That should serve as a stopgap so that we do the same formatting across all changes.
