### ISSUE TITLE
Fluctuating Billing Dashboard

### ISSUE THREAD

**Issue by JaynouOliver** [aws/karpenter-core#770]
### Description

I do not know where to put this issue
**Observed Behavior**: I created a new IAM user and I can see the billing dashboard fluctuating

**Expected Behavior**: The screen should be steady and show me billings

Please refer to this video  - 
https://photos.app.goo.gl/VtAav6zpH8Ng3Q9y8

**Comment by engedaam** [comment]
@JaynouOliver You're best option will be to contact AWS support. If you are seeing any karpenter related issue, please feel free to open a new issue.

**Comment by JaynouOliver** [comment]
Thank you
