### ISSUE TITLE
Supporting stuck node metrics/ events

### ISSUE THREAD

**Issue by garvinp-stripe** [aws/karpenter-core#796]
### Description

**What problem are you trying to solve?**
https://github.com/aws/karpenter-core/issues/743
As explained here sometimes we get nodes that are stuck during termination due to various reason (like PDB). As the cluster operator we would like to be able to figure out when nodes are in these situations. 

Proposals:
- Metric that tracks node up time after termination.
- Based on an user inputted timeout N:
   - Events on stuck pods on node causing termination to not proceed after N 
   - Labeling nodes that are stuck after N

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Metric that tracks node up time after termination

**Comment by jonathan-innis** [comment]
> Metric that tracks node up time after termination

Could you use the node `deletionTimestamp` to model this for yourself with `kube-state`? I'm curious if the information for the termination is already present in the apiserver or if we truly need to model this within Karpenter?

**Comment by jonathan-innis** [comment]
> - Based on an user inputted timeout N:
>    - Events on stuck pods on node causing termination to not proceed after N
>    - Labeling nodes that are stuck after N

In terms of the wholesale solution for removing nodes after a certain time after their deletion timestamp has been set, I'd really like to see us just implement the graceful termination mechanism within Karpenter and then extend it out to other CRDs for a long-term upstream solution as called out by @sftim. We could put something into the `nodeClaim` like `spec.gracefulTermination` which would map into the NodePool at `nodePool.spec.template.spec.gracefulTermination`.

**Comment by garvinp-stripe** [comment]
> > Metric that tracks node up time after termination
> 
> Could you use the node `deletionTimestamp` to model this for yourself with `kube-state`? I'm curious if the information for the termination is already present in the apiserver or if we truly need to model this within Karpenter?

Ah I guess I never saw that because we are running an older kube-state-metric but that should work

> > * Based on an user inputted timeout N:
> >   
> >   * Events on stuck pods on node causing termination to not proceed after N
> >   * Labeling nodes that are stuck after N
> 
> In terms of the wholesale solution for removing nodes after a certain time after their deletion timestamp has been set, I'd really like to see us just implement the graceful termination mechanism within Karpenter and then extend it out to other CRDs for a long-term upstream solution as called out by @sftim. We could put something into the `nodeClaim` like `spec.gracefulTermination` which would map into the NodePool at `nodePool.spec.template.spec.gracefulTermination`.

Ya would like to see that too. I suspect if this was implement we may still need a similar metric but for nodes living > deletionTimestamp + gracefulTermination.

**Comment by jonathan-innis** [comment]
> nodes living > deletionTimestamp + gracefulTermination but that change can wait

Yeah, I assume at that point, we would assume that the Karpenter controller is not behaving like it should since once we have that feature in we should just always react to NodeClaims/Nodes that are past their graceful termination period.
